### ISSUE TITLE
Stop doesn't work

### ISSUE THREAD

**Issue by thomasaarholt** [stefsmeets/InsteaDMatic#1]
Once one has started the InsteaDMatic Control so it is waiting for a tilt, pressing "Stop" does nothing.

**Comment by stefsmeets** [comment]
I see why that is useful, this is easily added by adding a check `if ( loop )` here: https://github.com/stefsmeets/InsteaDMatic/blob/f0deed4ea81ee22b7da26739e4ba09dfdec4bedc/insteadmatic.s#L349
